### ISSUE TITLE
Webpack-dev-server doesn't rebundle in response to shared folder changes (OSX)

### ISSUE THREAD

**Issue by edmyersjr** [danielwrobert/vagrant-react-webpack#1]
I had to make a few changes to the webpack.config to get live-reloads working when using webpack-dev-server. If I make a file change from within the vagrant machine, Webpack automatically re-bundles and reloads the browser, but if the change originates from OSX the modules aren't reloaded. This can be worked around by enabling polling in in the webpack.config.js:

// in webpack.config.js
devServer: {
    watchOptions: {
      aggregateTimeout: 300,
      poll: 1000
    }
  },

There may be a better solution - I'm REALLY new to webpack and react, but this resolved the issue for my immediate needs.

I also found it strange that you have to navigate into the /public folder after browsing to localhost:8881. if you change your output to:

// in webpack.config.js
output: {
    path: path.resolve(__dirname, "public"),
    publicPath: "/",
    filename: "scripts/main.js",
    sourceMapFilename: 'scripts/main.js.map'
}

then alter your start script in package.json to use --content-base, the server shows the app as if it were in the root.

// in package.json

"scripts": {
    //...
    "start": "webpack-dev-server --content-base public/ --progress --inline --host 0.0.0.0 --port 8881",
    //....
}

These are just suggestions, otherwise this is a great box. I'm really happy I found it. Thanks for sharing!

**Comment by danielwrobert** [comment]
Awesome, I really appreciate this feedback! Sorry for my very delayed reply. I kind of put this on the back-burner for a bit but just started getting back to poking around and updating it. Apparently I missed your issue altogether until now!

I've been tweaking/experimenting with this here and there to get a good workflow going so some things may be a bit rough still.

> I also found it strange that you have to navigate into the /public folder after browsing to localhost:8881.

Yes, I also found that a bit odd but I hadn't really gotten around to looking into a solution. Your suggestion there looks like a very nice approach!

Thanks again for the feedback/suggestions and I'm glad you found the box! :)

**Comment by danielwrobert** [comment]
@edmyersjr - I added in the changes for the output path per your suggestion so you no longer need to navigate to /public.

With regards to the live-reloading from the local shared folder, I just added the `--watch-poll` flag to my start script in the _package.json_ file and that seems to do the trick.

More updates to come!
